apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-k8s
  template:
    metadata:
      labels:
        app: jenkins-k8s
    spec:
      containers:
        - name: jenkins-k8s-container
          image: jaga407/jenkins-k8s:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: BUILD_VERSION
              value: "1.0.0"
