apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-k8s
  template:
    metadata:
      labels:
        app: jenkins-k8s
    spec:
      containers:
      - name: jenkins-k8s-container
        image: jaga407/jenkins-k8s:latest
        ports:
       - containerPort: 80    
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-k8s-service
spec:
  selector:
    app: jenkins-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
