apiVersion: v1
kind: Service
metadata:
  name: jenkins-k8s-service
spec:
  type: NodePort  # or LoadBalancer for cloud
  selector:
    app: jenkins-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
